use std::fs::File;
use std::io::{BufRead, BufReader};

/// Returns a ```Vec<String>``` with the lines of the file that it receives.
///
/// # Example
///
/// File:
/// ```
/// # Generated by NetworkManager
/// search midominio
/// nameserver 192.168.8.1
/// nameserver 8.8.8.8
/// ```
///
/// Result:
/// ```
/// ['# Generated by NetworkManager',
/// 'search midominio',
/// 'nameserver 192.168.8.1',
/// 'nameserver 8.8.8.8']
/// ```

pub fn read_file_lines(filename: String) -> Vec<String> {
    let file = File::open(filename).unwrap();
    let reader = BufReader::new(file);

    let mut lines = Vec::new();
    for (_index, line) in reader.lines().enumerate() {
        let line = line.unwrap();
        lines.push(line);
    }

    lines
}
